using ServiceStack.DataAnnotations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pkpm.Entity.ElasticSearch
{
    [Alias("HNKY_CUR")]
    public partial class HNKY_CUR  
    {
       
        [Required]
        public string SYSPRIMARYKEY { get; set; }
        public string PROJECTNUM { get; set; }
        public string SENDSAMPLEMAN { get; set; }
        public string SENDSAMPLEMANTEL { get; set; }
        public string SAMPLENUM { get; set; }
        public string ENTRUSTNUM { get; set; }
        public string REPORTNUM { get; set; }
        public string SAMPLENAME { get; set; }
        public string STANDARDNAME { get; set; }
        public string CHECKTYPE { get; set; }
        public string STRUCTPART { get; set; }
        public string DEPUTYBATCH { get; set; }
        public string SAMPLEAMOUNT { get; set; }
        public string SAMPLESTATUS { get; set; }
        public string SAMPLEDISPOSEMODE { get; set; }
        public string SAMPLEDISPOSEPHASE { get; set; }
        public string SAMPLECHARGETYPE { get; set; }
        public string PRODUCEFACTORY { get; set; }
        public DateTime? PRODUCEDATE { get; set; }
        public DateTime? REPORTCONSENTDATE { get; set; }
        public DateTime? ENTRUSTDATE { get; set; }
        public DateTime? CHECKDATE { get; set; }
        public DateTime? AUDITINGDATE { get; set; }
        public DateTime? APPROVEDATE { get; set; }
        public DateTime? PRINTDATE { get; set; }
        public string CHECKCONCLUSION { get; set; }
        public string CONCLUSIONCODE { get; set; }
        public string ACCEPTSAMPLEMAN { get; set; }
        public string FIRSTCHECKMAN { get; set; }
        public string SECONDCHECKMAN { get; set; }
        public string VERIFYMAN { get; set; }
        public string AUDITINGMAN { get; set; }
        public string APPROVEMAN { get; set; }
        public string PRINTMAN { get; set; }
        public string EXTENDMAN { get; set; }
        public string INSTRUMENTNUM { get; set; }
        public string INSTRUMENTNAME { get; set; }
        public string CHECKENVIRONMENT { get; set; }
        public string EXPLAIN { get; set; }
        public int? REPORTCONSENTDAYS { get; set; }
        public string WORKSTATION { get; set; }
        public string CHECKITEM1 { get; set; }
        public string SHEJIDENGJI { get; set; }
        public string XINGZHUANG { get; set; }
        public string CHICUN { get; set; }
        public string YANGHUTIAOJIAN { get; set; }
        public double? YANGHUXISHU { get; set; }
        public DateTime? CHENGXINGRIQI { get; set; }
        public int? LINQI { get; set; }
        public string CHENGXINGFANGFA { get; set; }
        public string JIANYANPIMINGCHEN { get; set; }
        public int? CHANG1 { get; set; }
        public int? CHANG2 { get; set; }
        public int? CHANG3 { get; set; }
        public int? KUAN1 { get; set; }
        public int? KUAN2 { get; set; }
        public int? KUAN3 { get; set; }
        public int? GAO1 { get; set; }
        public int? GAO2 { get; set; }
        public int? GAO3 { get; set; }
        public double? CHICUNXISHU { get; set; }
        public double? JIXIANGHEZAI1 { get; set; }
        public double? JIXIANGHEZAI2 { get; set; }
        public double? JIXIANGHEZAI3 { get; set; }
        public double? QIANGDU3 { get; set; }
        public double? QIANGDU2 { get; set; }
        public double? QIANGDU1 { get; set; }
        public string QIANGDUDAIBIAOZHI { get; set; }
        public double? BAIFENGBI { get; set; }
        public double? NEEDCHARGEMONEY { get; set; }
        public string COLLATEMAN { get; set; }
        public DateTime? COLLATEDATE { get; set; }
        public DateTime? VERIFYDATE { get; set; }
        public DateTime? EXTENDDATE { get; set; }
        public string BEFORESTATUS { get; set; }
        public string AFTERSTATUS { get; set; }
        public string TEMPERATURE { get; set; }
        public string HUMIDITY { get; set; }
        public string PDSTANDARDNAME { get; set; }
        public string BACKUPCOLUMN1 { get; set; }
        public string BACKUPCOLUMN2 { get; set; }
        public string BACKUPCOLUMN3 { get; set; }
        public string BACKUPCOLUMN4 { get; set; }
        public string BACKUPCOLUMN5 { get; set; }
        public string BACKUPCOLUMN6 { get; set; }
        public string BACKUPCOLUMN7 { get; set; }
        public string BACKUPCOLUMN8 { get; set; }
        public string BACKUPCOLUMN9 { get; set; }
        public string BACKUPCOLUMN10 { get; set; }
        public string BACKUPCOLUMN11 { get; set; }
        public string BACKUPCOLUMN12 { get; set; }
        public string BACKUPCOLUMN13 { get; set; }
        public string BACKUPCOLUMN14 { get; set; }
        public string BACKUPCOLUMN15 { get; set; }
        public string BACKUPCOLUMN16 { get; set; }
        public string BACKUPCOLUMN17 { get; set; }
        public string BACKUPCOLUMN18 { get; set; }
        public string BACKUPCOLUMN19 { get; set; }
        public string BACKUPCOLUMN20 { get; set; }
        public string BACKUPCOLUMN21 { get; set; }
        public string BACKUPCOLUMN22 { get; set; }
        public string BACKUPCOLUMN23 { get; set; }
        public string BACKUPCOLUMN24 { get; set; }
        public string BACKUPCOLUMN25 { get; set; }
        public string BACKUPCOLUMN26 { get; set; }
        public string BACKUPCOLUMN27 { get; set; }
        public string BACKUPCOLUMN28 { get; set; }
        public string BACKUPCOLUMN29 { get; set; }
        public string BACKUPCOLUMN30 { get; set; }
        public string WITNESSUNIT { get; set; }
        public string WITNESSMAN { get; set; }
        public string WITNESSMANNUM { get; set; }
        public string WITNESSMANTEL { get; set; }
        public string SUPERMAN { get; set; }
        public string SUPERUNIT { get; set; }
        public string TAKESAMPLEUNIT { get; set; }
        public string TAKESAMPLEMANNUM { get; set; }
        public string TAKESAMPLEMAN { get; set; }
        public string TAKESAMPLEMANTEL { get; set; }
        public string INSPECTMAN { get; set; }
        public string CONSTRACTIONUNIT { get; set; }
        public DateTime? FACTCHECKDATE { get; set; }
        public string PROJECTNAME { get; set; }
        public string REPORTSTYLESTYPES { get; set; }
        public string SENDTOWEB { get; set; }
        public string CONSTRACTUNIT { get; set; }
        public string QIANGDUZHI { get; set; }
        public int? YQLQ { get; set; }
        public string IMPORTDATANUM { get; set; }
        public string ENTRUSTUNIT { get; set; }
        public string LJWD { get; set; }
        public string QIANGDUGUOCHENGZHI { get; set; }
        public double? SHEJIQIANGDU { get; set; }
        public string LAYERCODE { get; set; }
        public string unitCode { get; set; }
        public int? DATATYPE { get; set; }
        public string CODEBAR { get; set; }
        public string AUTODEFINENOTE { get; set; }
        public string HAINANREGID { get; set; }
        public string HAINANENTRUSTSHEETID { get; set; }
        public string HAINANENTRUSTNUM { get; set; }
        public string HAINANCHECKTYPE2 { get; set; }
        public string HAINANSAMPLENUM { get; set; }
        public string GOUJIANNAME { get; set; }
        public string TESTBATCH { get; set; }
        public string ENTRUSTUNITID { get; set; }
        public string HAINANITEMID { get; set; }
        public string HAINANITEMNUM { get; set; }
        public string HAINANITEMNAME { get; set; }
        public string HAINANPROJECTID { get; set; }
        public string HAINANPROJECTNUM { get; set; }
        public string HAINANUNITPROJECTNAME { get; set; }
        public string WTSJLX { get; set; }
        public string CQPART { get; set; }
        public string WENDU { get; set; }
        public string CONTRACTNUM { get; set; }
        public string POSITION { get; set; }
        public string SUPERVISIONNUM { get; set; }
        public double? QIANGDUAVG { get; set; }
        public DateTime? YANGHUBDATE { get; set; }
        public DateTime? YANGHUEDATE { get; set; }
        public int? YANGHUDAYS { get; set; }
        public string TASKNUM { get; set; }
        public string LYTBAZH { get; set; }
        public string QIANGDUZHEHEZHI { get; set; }
        public DateTime? REQUESTCHECKDATE { get; set; }
        public string RECORDNUM { get; set; }
        public string CL1 { get; set; }
        public string CLGG1 { get; set; }
        public string CLCD1 { get; set; }
        public string CLZL1 { get; set; }
        public string DWB1 { get; set; }
        public string CL2 { get; set; }
        public string CLGG2 { get; set; }
        public string CLCD2 { get; set; }
        public string CLZL2 { get; set; }
        public string DWB2 { get; set; }
        public string CL3 { get; set; }
        public string CLGG3 { get; set; }
        public string CLCD3 { get; set; }
        public string CLZL3 { get; set; }
        public string DWB3 { get; set; }
        public string CL4 { get; set; }
        public string CLGG4 { get; set; }
        public string CLCD4 { get; set; }
        public string CLZL4 { get; set; }
        public string DWB4 { get; set; }
        public string CL5 { get; set; }
        public string CLGG5 { get; set; }
        public string CLCD5 { get; set; }
        public string CLZL5 { get; set; }
        public string DWB5 { get; set; }
        public string CL6 { get; set; }
        public string CLGG6 { get; set; }
        public string CLCD6 { get; set; }
        public string CLZL6 { get; set; }
        public string DWB6 { get; set; }
        public string CL7 { get; set; }
        public string CLGG7 { get; set; }
        public string CLCD7 { get; set; }
        public string CLZL7 { get; set; }
        public string DWB7 { get; set; }
        public string CL8 { get; set; }
        public string CLGG8 { get; set; }
        public string CLCD8 { get; set; }
        public string CLZL8 { get; set; }
        public string DWB8 { get; set; }
        public double? SPEEDMAX { get; set; }
        public double? SPEEDMIN { get; set; }
        public double? SPEEDAVG { get; set; }
        public string MAKEDEPICT { get; set; }
        public double? TTJDBZ { get; set; }
        public string CHECKITEM1PD { get; set; }
        public string SAMPLEEXPLAIN { get; set; }
        public string TAKEPOSITION { get; set; }
        public string HGKS { get; set; }
        public string CUSTOMID { get; set; }
    }

    [Alias("SJKY_CUR")]
    public partial class SJKY_CUR  
    { 
        [Required]
        public string SYSPRIMARYKEY { get; set; }
        public string CUSTOMID { get; set; }
        public string PROJECTNUM { get; set; }
        public string SENDSAMPLEMAN { get; set; }
        public string SENDSAMPLEMANTEL { get; set; }
        public string SAMPLENUM { get; set; }
        public string ENTRUSTNUM { get; set; }
        public string REPORTNUM { get; set; }
        public string SAMPLENAME { get; set; }
        public string STANDARDNAME { get; set; }
        public string CHECKTYPE { get; set; }
        public string STRUCTPART { get; set; }
        public string DEPUTYBATCH { get; set; }
        public string SAMPLEAMOUNT { get; set; }
        public string SAMPLESTATUS { get; set; }
        public string SAMPLEDISPOSEMODE { get; set; }
        public string SAMPLEDISPOSEPHASE { get; set; }
        public string SAMPLECHARGETYPE { get; set; }
        public string PRODUCEFACTORY { get; set; }
        public DateTime? PRODUCEDATE { get; set; }
        public DateTime? REPORTCONSENTDATE { get; set; }
        public DateTime? ENTRUSTDATE { get; set; }
        public DateTime? CHECKDATE { get; set; }
        public DateTime? AUDITINGDATE { get; set; }
        public DateTime? APPROVEDATE { get; set; }
        public DateTime? PRINTDATE { get; set; }
        public string CHECKCONCLUSION { get; set; }
        public string CONCLUSIONCODE { get; set; }
        public string ACCEPTSAMPLEMAN { get; set; }
        public string FIRSTCHECKMAN { get; set; }
        public string SECONDCHECKMAN { get; set; }
        public string VERIFYMAN { get; set; }
        public string AUDITINGMAN { get; set; }
        public string APPROVEMAN { get; set; }
        public string PRINTMAN { get; set; }
        public string EXTENDMAN { get; set; }
        public string INSTRUMENTNUM { get; set; }
        public string INSTRUMENTNAME { get; set; }
        public string CHECKENVIRONMENT { get; set; }
        public string EXPLAIN { get; set; }
        public int? REPORTCONSENTDAYS { get; set; }
        public string WORKSTATION { get; set; }
        public string AUTODEFINENOTE { get; set; }
        public string SHAJIANGPINZHONG { get; set; }
        public string WAIJIAJICANLIANG { get; set; }
        public string SHEJIQIANGDUDENGJI { get; set; }
        public string SIZE { get; set; }
        public string YANGHUTIAOJIAN { get; set; }
        public DateTime? CHENGXINGDATE { get; set; }
        public double? LINGQI { get; set; }
        public string WAIJIAJIPINZHONG { get; set; }
        public string CANHELIAOPINZHONG { get; set; }
        public double? CHANG1 { get; set; }
        public double? CHANG2 { get; set; }
        public double? CHANG3 { get; set; }
        public double? CHANG4 { get; set; }
        public double? CHANG5 { get; set; }
        public double? CHANG6 { get; set; }
        public double? KUAN1 { get; set; }
        public double? KUAN2 { get; set; }
        public double? KUAN3 { get; set; }
        public double? KUAN4 { get; set; }
        public double? KUAN5 { get; set; }
        public double? KUAN6 { get; set; }
        public double? GAO1 { get; set; }
        public double? GAO2 { get; set; }
        public double? GAO3 { get; set; }
        public double? GAO4 { get; set; }
        public double? GAO5 { get; set; }
        public double? GAO6 { get; set; }
        public double? JIXIANHEZAI1 { get; set; }
        public double? JIXIANHEZAI2 { get; set; }
        public double? JIXIANHEZAI3 { get; set; }
        public double? JIXIANHEZAI4 { get; set; }
        public double? JIXIANHEZAI5 { get; set; }
        public double? JIXIANHEZAI6 { get; set; }
        public double? QIANGDU1 { get; set; }
        public double? QIANGDU2 { get; set; }
        public double? QIANGDU3 { get; set; }
        public double? QIANGDU4 { get; set; }
        public double? QIANGDU5 { get; set; }
        public double? QIANGDU6 { get; set; }
        public double? QIANGDUBAIFENBI { get; set; }
        public string QIANGDUDAIBIAOZHI { get; set; }
        public double? QIANGDUMIN { get; set; }
        public double? QIANGDUMAX { get; set; }
        public string CHENGXINGFANGFA { get; set; }
        public string PEIHEBI { get; set; }
        public string CHOUDU { get; set; }
        public string FENCENGDU { get; set; }
        public string BEICHAHAO { get; set; }
        public string KUAICAIPINZHONG { get; set; }
        public string PIHAO { get; set; }
        public string CHECKITEM1 { get; set; }
        public double? NEEDCHARGEMONEY { get; set; }
        public string COLLATEMAN { get; set; }
        public DateTime? COLLATEDATE { get; set; }
        public DateTime? VERIFYDATE { get; set; }
        public DateTime? EXTENDDATE { get; set; }
        public string BEFORESTATUS { get; set; }
        public string AFTERSTATUS { get; set; }
        public string TEMPERATURE { get; set; }
        public string HUMIDITY { get; set; }
        public string PDSTANDARDNAME { get; set; }
        public string BACKUPCOLUMN1 { get; set; }
        public string BACKUPCOLUMN2 { get; set; }
        public string BACKUPCOLUMN3 { get; set; }
        public string BACKUPCOLUMN4 { get; set; }
        public string BACKUPCOLUMN5 { get; set; }
        public string BACKUPCOLUMN6 { get; set; }
        public string BACKUPCOLUMN7 { get; set; }
        public string BACKUPCOLUMN8 { get; set; }
        public string BACKUPCOLUMN9 { get; set; }
        public string BACKUPCOLUMN10 { get; set; }
        public string BACKUPCOLUMN11 { get; set; }
        public string BACKUPCOLUMN12 { get; set; }
        public string BACKUPCOLUMN13 { get; set; }
        public string BACKUPCOLUMN14 { get; set; }
        public string BACKUPCOLUMN15 { get; set; }
        public string BACKUPCOLUMN16 { get; set; }
        public string BACKUPCOLUMN17 { get; set; }
        public string BACKUPCOLUMN18 { get; set; }
        public string BACKUPCOLUMN19 { get; set; }
        public string BACKUPCOLUMN20 { get; set; }
        public string BACKUPCOLUMN21 { get; set; }
        public string BACKUPCOLUMN22 { get; set; }
        public string BACKUPCOLUMN23 { get; set; }
        public string BACKUPCOLUMN24 { get; set; }
        public string BACKUPCOLUMN25 { get; set; }
        public string BACKUPCOLUMN26 { get; set; }
        public string BACKUPCOLUMN27 { get; set; }
        public string BACKUPCOLUMN28 { get; set; }
        public string BACKUPCOLUMN29 { get; set; }
        public string BACKUPCOLUMN30 { get; set; }
        public string WITNESSUNIT { get; set; }
        public string WITNESSMAN { get; set; }
        public string WITNESSMANNUM { get; set; }
        public string WITNESSMANTEL { get; set; }
        public string SUPERMAN { get; set; }
        public string SUPERUNIT { get; set; }
        public string TAKESAMPLEUNIT { get; set; }
        public string TAKESAMPLEMANNUM { get; set; }
        public string TAKESAMPLEMAN { get; set; }
        public string TAKESAMPLEMANTEL { get; set; }
        public string INSPECTMAN { get; set; }
        public string CONSTRACTIONUNIT { get; set; }
        public DateTime? FACTCHECKDATE { get; set; }
        public string PROJECTNAME { get; set; }
        public string REPORTSTYLESTYPES { get; set; }
        public string SENDTOWEB { get; set; }
        public string CONSTRACTUNIT { get; set; }
        public int? YQLQ { get; set; }
        public string IMPORTDATANUM { get; set; }
        public string ENTRUSTUNIT { get; set; }
        public double? HSXS { get; set; }
        public string unitCode { get; set; }
        public int? DATATYPE { get; set; }
        public string CODEBAR { get; set; }
        public string TESTBATCH { get; set; }
        public string CONTRACTNUM { get; set; }
        public string POSITION { get; set; }
        public string SUPERVISIONNUM { get; set; }
        public double? QIANGDUAVG { get; set; }
        public DateTime? REQUESTCHECKDATE { get; set; }
        public string SAMPLEEXPLAIN { get; set; }
        public string TAKEPOSITION { get; set; }
        public string HGKS { get; set; }
    }
}
